### ISSUE TITLE
Compile won't work

### ISSUE THREAD

**Issue by ghost** [NullHypothesis/brdgrd#1]
cd brdgrd-master

make

ERROR:

cc brdgrd.c -Wall -Wextra -Wformat-security -O3 -fstack-protector-all -lnetfilter_queue -o brdgrd
brdgrd.c: In function ‘callback’:
brdgrd.c:169:27: warning: passing argument 2 of ‘nfq_get_payload’ from incompatible pointer type [-Wincompatible-pointer-types]
  if (nfq_get_payload(nfa, (char **) &packet) == -1) {
                           ^
In file included from brdgrd.c:29:0:
/usr/local/include/libnetfilter_queue/libnetfilter_queue.h:122:12: note: expected ‘unsigned char **’ but argument is of type ‘char **’
 extern int nfq_get_payload(struct nfq_data *nfad, unsigned char **data);
            ^~~~~~~~~~~~~~~
brdgrd.c:148:57: warning: unused parameter ‘nfmsg’ [-Wunused-parameter]
 int callback( struct nfq_q_handle *qh, struct nfgenmsg *nfmsg, struct nfq_data *nfa,
                                                         ^~~~~
brdgrd.c:149:8: warning: unused parameter ‘data’ [-Wunused-parameter]
  void *data ) {
        ^~~~

how to FIX it? PLEASE HELP, thanks!

**Comment by ghost** [comment]
when I type in terminal "brdgrd"

output:
nfq_unbind_pf() failed. Exiting because libnetfilter_queue init failed

when I type:
screen -dmS brdgrd setcap cap_net_admin=ep ./brdgrd -v

no output error, hmm...

**Comment by NullHypothesis** [comment]
You cannot run brdgrd as a normal user. You either have to run it as root or use setcap.

> when I type:
screen -dmS brdgrd setcap cap_net_admin=ep ./brdgrd -v
>
> no output error, hmm...

Did it work after that?

Also, I believe that brdgrd is no longer effective against the GFW.

**Comment by ghost** [comment]
wont't work, I deleted it... Greetz!
